timeout: '3600s'

steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'build'
          - '-t'
          - 'gcr.io/${PROJECT_ID}/annotationstudio:${SHORT_SHA}'
          - '-f'
          - './amd64.Dockerfile'
          - '.'

    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'tag'
          - 'gcr.io/${PROJECT_ID}/annotationstudio:${SHORT_SHA}'
          - 'gcr.io/${PROJECT_ID}/annotationstudio:latest'

images: ['gcr.io/${PROJECT_ID}/annotationstudio:${SHORT_SHA}',
         'gcr.io/${PROJECT_ID}/annotationstudio:latest']
