version: "3"

services:
  label-studio:
    container_name: label-studio
    build:
        context: .
        dockerfile: amd64.Dockerfile
    volumes:
      - ./cloudstorage:/cloudstorage
      - ./data:/data
#    command:
#    - /bin/bash
#    - -c
#    - |
#        label-studio init ${PROJECT_NAME:-annotation_project}
#        label-studio start ${PROJECT_NAME:-annotation_project} ${INIT_COMMAND} -b --host 0.0.0.0 --port ${PORT:-8888}
    ports:
      - "8888:8888"
    restart: always
